assignment/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mysite/',include('mysite.urls', namespace="mysite"))
]

mysite/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.base,name="base"), #http://localhost:8000/blog
    url(r'^me_index/$', views.me_index,name="me_index"), #http://localhost:8000/blog
    url(r'^me_new/$',views.me_new, name="me_new"),  #http://localhost:8000/blog/new/ 뷰에있는 포스트뉴에 있는 걸가져올거야
    url(r'^(?P<me_id>\d+)/$', views.me_detail, name="me_detail"), #http://localhost:8000/blog/1
    url(r'^(?P<me_id>\d+)/edit/$', views.me_edit, name="me_edit"), #http://localhost:8000/blog/edit
    url(r'^(?P<me_id>\d+)/delete/$', views.me_delete, name="me_delete"), #http://localhost:8000/blog/edit

    url(r'^ask_new/$',views.ask_new, name="ask_new"),  #http://localhost:8000/blog/new/ 뷰에있는 포스트뉴에 있는 걸가져올거야
    url(r'^ask_index/$',views.ask_index, name="ask_index"),        
    url(r'^ask_(?P<ask_id>\d+)/$', views.ask_detail, name="ask_detail"), #http://localhost:8000/blog/1
    url(r'^ask_(?P<ask_id>\d+)/edit/$', views.ask_edit, name="ask_edit"), #http://localhost:8000/blog/edit
    url(r'^ask_(?P<ask_id>\d+)/delete/$', views.ask_delete, name="ask_delete"), #http://localhost:8000/blog/edit
    url(r'^ask_(?P<ask_id>\d+)/comment/$', views.add_comment_to_ask, name="add_comment_to_ask"), #http://localhost:8000/blog/me/123/comment
    url(r'^comment_(?P<comment_id>\d+)/delete/$', views.comment_delete, name="comment_delete"), #http://localhost:8000/blog/me/123/comment

]
#ask index

mysite/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
# Create your models here.

class Me(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)#객체 생성시ㅏㄱ    #애네는 거의 필수로
    updated_at = models.DateTimeField(auto_now=True)#객체 변경시 간

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("mysite:Me_detail", kwargs={"Me_id": self.id})#디테일로가는데 포스트아이디가지고가자


class Ask(models.Model):
    nickname = models.CharField(max_length=100,default = "guest")
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)#객체 생성시ㅏㄱ    #애네는 거의 필수로
    updated_at = models.DateTimeField(auto_now=True)#객체 변경시 간

    def __str__(self):
        return self.text
    def get_absolute_url(self):
        return reverse("mysite:Ask_detail", kwargs={"Ask_id": self.id})#디테일로가는데 포스트아이디가지고가자

class Comment(models.Model):
    post = models.ForeignKey('mysite.Ask',on_delete=models.CASCADE,related_name='comments')
    nickname = models.CharField(max_length=200,default = "root")
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    #a=Post.objects.get(id=1)
    #a.comments=>글 a에 달린 comment들의 query set
    def __str__(self):
        return self.text
# Create your models here.

mysite/forms.py
from django import forms
from .models import Me, Ask,Comment

class MeForm(forms.ModelForm):
    class Meta:
        model =Me
        fields = {'title','text',}

class AskForm(forms.ModelForm):
    class Meta:
        model =Ask
        fields = {'nickname','text',}

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {'nickname','text',}

mysite/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse
from .models import Me,Ask,Comment
from .forms import MeForm, CommentForm,AskForm


# Create your views here


def base(request):
  return render(request, 'mysite/base.html')

def me_new(request):
  if request.method == 'ME':
      form = MeForm(request.ME)
      if form.is_valid():
          me = form.save()
          return redirect('mysite:me_index')
  else:
      form =MeForm()    #생성

  return render(request,'mysite/me_new.html',{
      'form':form,
  })

def me_detail(request,me_id):#read를 한다 객체를 가져온다
  me = Me.objects.get(id=me_id)
  
  return render(request,'mysite/me_detail.html', {
      "me":me,
  })

def me_index(request):
  me_all=Me.objects.all()  #모든객체 가져와
  return render(request, 'mysite/me_index.html',{
      'me_all':me_all,
  })

def me_edit(request,me_id):
  me=get_object_or_404(Me,id=me_id)  #이걸 포스트에 담겠다

  if request.method == 'ME':
      form = MeForm(request.ME,instance=me)
      if form.is_valid():
          me = form.save()
          return redirect(me)
  else:
      form =MeForm(instance=me)    #생성

  return render(request,'mysite/me_new.html',{
      'form':form,
  })
def me_delete(request,me_id):
  me = get_object_or_404(Me,id=me_id)
  me.delete()
  return redirect('mysite:me_index')

def ask_new(request):
  if request.method == 'ASK':
      form = AskForm(request.ASK)
      if form.is_valid():
          ask = form.save()
          return redirect('mysite:ask_index')
  else:
      form =AskForm()    #생성

  return render(request,'mysite/ask_new.html',{
      'form':form,
  })

def ask_detail(request,ask_id):#read를 한다 객체를 가져온다
  ask = Ask.objects.get(id=ask_id)
  comment_form=CommentForm()
  
  return render(request,'mysite/ask_detail.html', {
      "ask":ask,
      "comment_form":comment_form,
  })

def ask_index(request):
  ask_all=Ask.objects.all()  #모든객체 가져와
  return render(request, 'mysite/ask_index.html',{
      'ask_all':ask_all,
  })

def ask_edit(request,ask_id):
  ask=get_object_or_404(Ask,id=ask_id)  #이걸 포스트에 담겠다

  if request.method == 'ASK':
      form = AskForm(request.ASK,instance=ask)
      if form.is_valid():
          ask = form.save()
          return redirect(ask)
  else:
      form =AskForm(instance=ask)    #생성

  return render(request,'mysite/ask_new.html',{
      'form':form,
  })
def ask_delete(request,ask_id):
  ask = get_object_or_404(Ask,id=ask_id)
  ask.delete()
  return redirect('mysite:ask_index')

def add_comment_to_ask(request,ask_id):
  ask=get_object_or_404(Ask,id=ask_id)
  if request.method == "ASK":
      form = CommentForm(request.ASK)
      if form .is_valid() :
          comment = form.save(commit=False)
          comment.ask = ask
          comment.save()
  return redirect(ask)
def comment_delete(request,comment_id):
  comment = get_object_or_404(Comment, id=comment_id)
  comment.delete()
  return redirect(comment.ask)
  

mysite/templates/mysite/ask_detail.html
{%load static%}

<h1>Ask</h1>

질문:{{ask.text}}
{% block content%}
<html>
<head>
    <style>
        body{
            background-image: url('https://www.suyongso.com/files/attach/images/115/242/786/015/10d4672110f57863418c21bf2b964539.jpg');
    
        }
        </style>
</head>
<hr>
<a href="{% url 'mysite:ask_edit' ask.id%} ">수정하기</a>
<a href="{% url 'mysite:ask_delete' ask.id%}" onclick="return confirm('지울건가요')"> 삭제</a>

<hr>
  <p>댓글 {{ ask.comments.count }}개</p>
  
    {% for comment in ask.comments.all %}
      <div>
        <div class="float-right">{{ comment.created_date }}</div>
        <strong>{{ comment.nickname }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
        <div class="btn-group btn-group-sm" role="group">
          <a href="{% url 'mysite:comment_delete' comment_id=comment.id %}" class="btn btn-secondary">삭제</a>
        </div>
        <hr>
      </div>
    {% empty %}
        <p>아직 아무 댓글이 없어요 :(</p>
    {% endfor %}<br>
    <form action="{%url 'mysite:add_comment_to_ask' ask_id=ask.id%}"method="ASK">{%csrf_token%}
        {{comment_form.as_p}}
        <button type="submit" class="save btn btn-default">작성</button>
{% endblock %}
</html>

mysite/templates/mysite/ask_index.html
{%load static%}
<html>
    
    <head>
        <style>
                body{
                    background-image: url('https://www.suyongso.com/files/attach/images/115/242/786/015/10d4672110f57863418c21bf2b964539.jpg');
            
                }
        </style>
    </head>
    
    <body>
            <nav>
                    <h2>목차</h2>
                    <ol>
                        
                        <li><a href="{% url 'mysite:me_index' %}">간단한 소개</a></li>
                        <li><a href ="{% url 'mysite:ask_index' %}">QnA</a></li>
                        
                    </ol>
                </nav>
                <h1 >   Ask Me</h1>
        <div class="container">
            <table border=1>
                <tbody>
                    <tr>
                        <th>제목</th>

                        <th>생성일</th>
                    </tr>
                </tbody>
                <tbody>
                {% for ask in ask_all %}
                    <tr>
                        <td><a href="{% url 'mysite:ask_detail' ask.id %}">{{ask.text}}</a></td>

                        <td>{{ask.updated_at}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <form action="{%url 'mysite:ask_new'%}"method="ASK">{%csrf_token%}
                    {{ask_form.as_p}}
                    <button type="submit" class="save btn btn-default">질문추가</button>
            
        </div>
    </body>
    
</html>

mysite/templates/mysite/ask_new.html
<head>
        <style>
            body{
                background-image: url('https://www.suyongso.com/files/attach/images/115/242/786/015/10d4672110f57863418c21bf2b964539.jpg');
        
            }
        </style>
</head>
<h1>새 질문 생성</h1>

<form action="" method="ask">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>

    <input type="submit" value="작성">
</form>

mysite/templates/mysite/base.html
{%load static %}
<html>
    <head>
        <title>ASK페이지</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> <!--부트스트렙 추가해주기  -->
        <link rel="stylesheet" href="{% static 'css/mysite.css'%}">
        
                <style>
                    body{
                        background-image: url('https://www.suyongso.com/files/attach/images/115/242/786/015/10d4672110f57863418c21bf2b964539.jpg');
                
                    }
                </style>
        
    </head>
    <body>
            <nav>
                <h2>목차</h2>
                <ol>
                    
                    <li><a href="{% url 'mysite:me_index' %}">간단한 소개</a></li>
                    <li><a href ="{% url 'mysite:ask_index' %}">QnA</a></li>
                    
                </ol>
            </nav>
    </body>
</html>

mysite/templates/mysite/me_detail.html
{%load static%}
<head>
        <style>
            body{
                background-image: url('https://www.suyongso.com/files/attach/images/115/242/786/015/10d4672110f57863418c21bf2b964539.jpg');
        
            }
            </style>
</head>
<h1>list</h1>
{{me.title}}
<br>
{{me.text}}
{% block content%}
<html>
<hr>
<a href="{% url 'mysite:me_edit' me.id%} ">수정하기</a>
<a href="{% url 'mysite:me_delete' me.id%}" onclick="return confirm('지울건가요')"> 삭제</a>

<hr>

</html>

{% endblock%}

mysite/templates/mysite/me_index.html
{%load static%}
<html>
    
    <head>
        <title>My페이지</title>
    <style>
    body{
        background-image: url('https://www.suyongso.com/files/attach/images/115/242/786/015/10d4672110f57863418c21bf2b964539.jpg');

    }
    </style> 
    </head>
    <body>
            <nav>
                    <h2>목차</h2>
                    <ol>
                        
                        <li><a href="{% url 'mysite:me_index' %}">간단한 소개</a></li>
                        <li><a href ="{% url 'mysite:ask_index' %}">QnA</a></li>
                        
                    </ol>
                </nav>
        <h1>   About Me</h1>
        <div class="container">
            <table border=1>
                <tbody>
                    <tr>
                        <th>제목</th>
                        <th>생성일</th>
                    </tr>
                </tbody>
                <tbody>
                {% for me in me_all %}
                    <tr>
                        <td><a href="{% url 'mysite:me_detail' me.id %}">{{me.title}}</a></td>
                        <td>{{me.updated_at}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <form action="{%url 'mysite:me_new'%}"method="ME">{%csrf_token%}
                    {{me_form.as_p}}
                    <button type="submit" class="save btn btn-default">소개추가</button>
            
        </div>
    </body>
    
</html>


  

mysite/templates/mysite/me_new.html
<head>
        <style>
            body{
                background-image: url('https://www.suyongso.com/files/attach/images/115/242/786/015/10d4672110f57863418c21bf2b964539.jpg');
        
            }
            </style>
</head>
<h1>새 소개 생성</h1>

<form action="" method="me">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>

    <input type="submit" value="작성">
</form>